# Generated by Django 4.2.16 on 2024-10-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_stockdata_close_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(max_length=10)),
                ('predicted_price', models.FloatField()),
                ('actual_price', models.FloatField(blank=True, null=True)),
                ('prediction_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
